### ISSUE TITLE
More Clouds

### ISSUE THREAD

**Issue by Qrokqt** [SafranCassiopee/php-metar-decoder#24]
Currently it looks like only 4 cloud layers are allowed.

[The handbook](https://www.ofcm.gov/publications/fmh/FMH1/FMH1_2017.pdf) says up to 6 layers can be reported (section 9.5.2).

Here's an example with 5
SPECI KADW 191705Z AUTO 27008KT 10SM -DZ FEW080 FEW110 FEW130 BKN150  BKN190 33/22 A2982 RMK AO2 DZB05 SLP102

**Comment by inouire** [comment]
Hi Qrokqt, thank you for your feedback. This should be fixed by this commit https://github.com/SafranCassiopee/php-metar-decoder/commit/9c810434c45c19d298bc96b85c9a77fa64108524 which makes the parser support up to 6 layers.
